### ISSUE TITLE
Contains stale github.com/tufin/istio-discovery references

### ISSUE THREAD

**Issue by tmc** [istio-ecosystem/dns-discovery#4]
dns/server.go
11:	"github.com/tufin/istio-discovery/istio"

main.go
14:	"github.com/tufin/istio-discovery/dns"
15:	"github.com/tufin/istio-discovery/istio"

**Comment by dorkolog** [comment]
hi @tmc. your [PR](https://github.com/istio-ecosystem/dns-discovery/pull/5) was merged. Thanks !
